# start from base
FROM ubuntu:18.04

LABEL maintainer="Your Name <youremailaddress@provider.com>"

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

HEALTHCHECK --interval=10s --timeout=30s CMD curl --fail http://localhost:8080/ || exit 1

CMD [ "python", "./app.py" ]

STOPSIGNAL SIGKILL