apiVersion: apps/v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      matchLabels:
        run: my-nginx
    spec:
      containers:
      - name: deploy-container
        image: nginx
        ports:
        - containerPort: 80