apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  labels:
    apps: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
    matchExpressions:
      - {key: app, operators: In, values: [nginx]}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80