apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: nginx
  matchLabels:  env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd